export type QuizChoice = {
  id: 'A' | 'B' | 'C' | 'D'
  text: string
}

export type FoundationQuestion = {
  id: number
  category: string
  question: string
  choices: QuizChoice[]
  correctChoiceId: QuizChoice['id']
  explanation: string
}

export const financialLiteracyFoundationsQuestions: FoundationQuestion[] = [
  {
    id: 1,
    category: 'Income & Expenses',
    question: 'What is income?',
    choices: [
      { id: 'A', text: 'Money you spend' },
      { id: 'B', text: 'Money you receive' },
      { id: 'C', text: 'Money you borrow' },
      { id: 'D', text: 'Money you save' },
    ],
    correctChoiceId: 'B',
    explanation: 'Income is money received from salary, business, allowances, commissions, or other sources.',
  },
  {
    id: 2,
    category: 'Income & Expenses',
    question: 'What is an expense?',
    choices: [
      { id: 'A', text: 'Money received' },
      { id: 'B', text: 'Money invested' },
      { id: 'C', text: 'Money spent' },
      { id: 'D', text: 'Money borrowed' },
    ],
    correctChoiceId: 'C',
    explanation: 'An expense is money that leaves your possession to pay for goods or services.',
  },
  {
    id: 3,
    category: 'Income & Expenses',
    question: 'Which is an example of income?',
    choices: [
      { id: 'A', text: 'Salary' },
      { id: 'B', text: 'Grocery Purchase' },
      { id: 'C', text: 'Utility Bill' },
      { id: 'D', text: 'Loan Payment' },
    ],
    correctChoiceId: 'A',
    explanation: 'Salary is money you receive for work, so it is income.',
  },
  {
    id: 4,
    category: 'Income & Expenses',
    question: 'Which is an example of an expense?',
    choices: [
      { id: 'A', text: 'Salary' },
      { id: 'B', text: 'Bonus' },
      { id: 'C', text: 'Electricity Bill' },
      { id: 'D', text: 'Savings Deposit' },
    ],
    correctChoiceId: 'C',
    explanation: 'An electricity bill is money you pay for a service, so it is an expense.',
  },
  {
    id: 5,
    category: 'Income & Expenses',
    question: 'What happens when your expenses exceed your income?',
    choices: [
      { id: 'A', text: 'Savings increase' },
      { id: 'B', text: 'Debt may increase' },
      { id: 'C', text: 'Income doubles' },
      { id: 'D', text: 'Assets automatically grow' },
    ],
    correctChoiceId: 'B',
    explanation: 'When spending is higher than income, people may need to use savings or borrow money.',
  },
  {
    id: 6,
    category: 'Income & Expenses',
    question: 'Why is tracking expenses important?',
    choices: [
      { id: 'A', text: 'To spend more money' },
      { id: 'B', text: 'To understand where money goes' },
      { id: 'C', text: 'To increase debt' },
      { id: 'D', text: 'To avoid saving' },
    ],
    correctChoiceId: 'B',
    explanation: 'Tracking expenses shows where money goes and helps you make better spending decisions.',
  },
  {
    id: 7,
    category: 'Assets & Liabilities',
    question: 'What is an asset?',
    choices: [
      { id: 'A', text: 'Something you own that has value' },
      { id: 'B', text: 'Something you owe' },
      { id: 'C', text: 'A monthly bill' },
      { id: 'D', text: 'A loan payment' },
    ],
    correctChoiceId: 'A',
    explanation: 'An asset is something you own that has value, such as cash or savings.',
  },
  {
    id: 8,
    category: 'Assets & Liabilities',
    question: 'Which is an asset?',
    choices: [
      { id: 'A', text: 'Credit Card Debt' },
      { id: 'B', text: 'Personal Loan' },
      { id: 'C', text: 'Cash in Wallet' },
      { id: 'D', text: 'Unpaid Utility Bill' },
    ],
    correctChoiceId: 'C',
    explanation: 'Cash in your wallet is money you own, so it is an asset.',
  },
  {
    id: 9,
    category: 'Assets & Liabilities',
    question: 'What is a liability?',
    choices: [
      { id: 'A', text: 'Money you own' },
      { id: 'B', text: 'Money you owe' },
      { id: 'C', text: 'Money you save' },
      { id: 'D', text: 'Money you earn' },
    ],
    correctChoiceId: 'B',
    explanation: 'A liability is money you owe and must pay back.',
  },
  {
    id: 10,
    category: 'Assets & Liabilities',
    question: 'Which is a liability?',
    choices: [
      { id: 'A', text: 'Savings Account' },
      { id: 'B', text: 'Cash' },
      { id: 'C', text: 'Credit Card Balance' },
      { id: 'D', text: 'Emergency Fund' },
    ],
    correctChoiceId: 'C',
    explanation: 'A credit card balance is money owed to the card provider.',
  },
  {
    id: 11,
    category: 'Assets & Liabilities',
    question: 'If someone owes you money, it is generally considered:',
    choices: [
      { id: 'A', text: 'A receivable' },
      { id: 'B', text: 'An expense' },
      { id: 'C', text: 'A liability' },
      { id: 'D', text: 'Income' },
    ],
    correctChoiceId: 'A',
    explanation: 'A receivable is money expected to be paid to you.',
  },
  {
    id: 12,
    category: 'Assets & Liabilities',
    question: 'If you owe someone money, it is generally considered:',
    choices: [
      { id: 'A', text: 'An asset' },
      { id: 'B', text: 'A payable' },
      { id: 'C', text: 'Income' },
      { id: 'D', text: 'Savings' },
    ],
    correctChoiceId: 'B',
    explanation: 'A payable is money you need to pay to another person or group.',
  },
  {
    id: 13,
    category: 'Budgeting',
    question: 'What is a budget?',
    choices: [
      { id: 'A', text: 'A spending plan' },
      { id: 'B', text: 'A loan' },
      { id: 'C', text: 'A savings account' },
      { id: 'D', text: 'An investment' },
    ],
    correctChoiceId: 'A',
    explanation: 'A budget is a plan for how you want to use your money.',
  },
  {
    id: 14,
    category: 'Budgeting',
    question: 'Why create a budget?',
    choices: [
      { id: 'A', text: 'To control spending' },
      { id: 'B', text: 'To increase debt' },
      { id: 'C', text: 'To reduce income' },
      { id: 'D', text: 'To avoid saving' },
    ],
    correctChoiceId: 'A',
    explanation: 'A budget helps you choose where money should go before it is spent.',
  },
  {
    id: 15,
    category: 'Budgeting',
    question: 'Which is generally a need?',
    choices: [
      { id: 'A', text: 'Rent' },
      { id: 'B', text: 'Luxury Watch' },
      { id: 'C', text: 'Gaming Console' },
      { id: 'D', text: 'Designer Bag' },
    ],
    correctChoiceId: 'A',
    explanation: 'Rent is usually a need because it pays for a basic place to live.',
  },
  {
    id: 16,
    category: 'Budgeting',
    question: 'Which is generally a want?',
    choices: [
      { id: 'A', text: 'Food' },
      { id: 'B', text: 'Electricity' },
      { id: 'C', text: 'Luxury Handbag' },
      { id: 'D', text: 'Water Bill' },
    ],
    correctChoiceId: 'C',
    explanation: 'A luxury handbag is usually optional, so it is generally a want.',
  },
  {
    id: 17,
    category: 'Budgeting',
    question: 'What is the benefit of budgeting?',
    choices: [
      { id: 'A', text: 'Better financial visibility' },
      { id: 'B', text: 'Guaranteed wealth' },
      { id: 'C', text: 'Free money' },
      { id: 'D', text: 'No expenses' },
    ],
    correctChoiceId: 'A',
    explanation: 'Budgeting helps you see and guide your spending more clearly.',
  },
  {
    id: 18,
    category: 'Budgeting',
    question: 'A budget helps you answer:',
    choices: [
      { id: 'A', text: 'Where did my money go?' },
      { id: 'B', text: 'Who owes me?' },
      { id: 'C', text: 'What is inflation?' },
      { id: 'D', text: 'What is investing?' },
    ],
    correctChoiceId: 'A',
    explanation: 'A budget compares your spending plan with what actually happened.',
  },
  {
    id: 19,
    category: 'Savings & Emergency Funds',
    question: 'What is saving?',
    choices: [
      { id: 'A', text: 'Setting money aside for future use' },
      { id: 'B', text: 'Spending less money today only' },
      { id: 'C', text: 'Borrowing money' },
      { id: 'D', text: 'Paying bills' },
    ],
    correctChoiceId: 'A',
    explanation: 'Saving means keeping money for a future need, goal, or emergency.',
  },
  {
    id: 20,
    category: 'Savings & Emergency Funds',
    question: 'What is an emergency fund?',
    choices: [
      { id: 'A', text: 'Money reserved for unexpected expenses' },
      { id: 'B', text: 'A shopping fund' },
      { id: 'C', text: 'Vacation money' },
      { id: 'D', text: 'Investment capital' },
    ],
    correctChoiceId: 'A',
    explanation: 'An emergency fund is money saved for surprise needs like medical costs or urgent repairs.',
  },
  {
    id: 21,
    category: 'Savings & Emergency Funds',
    question: 'Which is a good reason to use an emergency fund?',
    choices: [
      { id: 'A', text: 'Medical Emergency' },
      { id: 'B', text: 'Buying a luxury watch' },
      { id: 'C', text: 'Upgrading a phone' },
      { id: 'D', text: 'Gambling' },
    ],
    correctChoiceId: 'A',
    explanation: 'A medical emergency is unexpected and important, which is what an emergency fund is for.',
  },
  {
    id: 22,
    category: 'Savings & Emergency Funds',
    question: 'Why should people save money?',
    choices: [
      { id: 'A', text: 'To prepare for future needs' },
      { id: 'B', text: 'To avoid budgeting' },
      { id: 'C', text: 'To increase debt' },
      { id: 'D', text: 'To eliminate income' },
    ],
    correctChoiceId: 'A',
    explanation: 'Savings help you prepare for goals, emergencies, and future responsibilities.',
  },
  {
    id: 23,
    category: 'Savings & Emergency Funds',
    question: 'What is one benefit of having savings?',
    choices: [
      { id: 'A', text: 'Financial security' },
      { id: 'B', text: 'More bills' },
      { id: 'C', text: 'More debt' },
      { id: 'D', text: 'Less income' },
    ],
    correctChoiceId: 'A',
    explanation: 'Savings provide a cushion when life becomes expensive or uncertain.',
  },
  {
    id: 24,
    category: 'Savings & Emergency Funds',
    question: 'Which is generally healthier financially?',
    choices: [
      { id: 'A', text: 'Spending everything earned' },
      { id: 'B', text: 'Saving a portion of income' },
      { id: 'C', text: 'Borrowing every month' },
      { id: 'D', text: 'Ignoring expenses' },
    ],
    correctChoiceId: 'B',
    explanation: 'Saving a portion of income helps build stability over time.',
  },
  {
    id: 25,
    category: 'Debt, Loans & Credit Cards',
    question: 'If you borrow money, what do you create?',
    choices: [
      { id: 'A', text: 'Income' },
      { id: 'B', text: 'Asset' },
      { id: 'C', text: 'Liability' },
      { id: 'D', text: 'Savings' },
    ],
    correctChoiceId: 'C',
    explanation: 'Borrowed money must be repaid, so it creates a liability.',
  },
  {
    id: 26,
    category: 'Debt, Loans & Credit Cards',
    question: 'If you lend money to a friend, is it an expense?',
    choices: [
      { id: 'A', text: 'Yes' },
      { id: 'B', text: 'No' },
    ],
    correctChoiceId: 'B',
    explanation: 'A loan is expected to be repaid, so it is not considered an expense.',
  },
  {
    id: 27,
    category: 'Debt, Loans & Credit Cards',
    question: 'If someone lends you PHP 10,000, is it income?',
    choices: [
      { id: 'A', text: 'Yes' },
      { id: 'B', text: 'No' },
    ],
    correctChoiceId: 'B',
    explanation: 'Borrowed money must be repaid and is therefore not income.',
  },
  {
    id: 28,
    category: 'Debt, Loans & Credit Cards',
    question: 'What is the best habit when using a credit card?',
    choices: [
      { id: 'A', text: 'Ignore due dates' },
      { id: 'B', text: 'Track spending and pay on time' },
      { id: 'C', text: 'Spend the entire credit limit' },
      { id: 'D', text: 'Only pay when reminded' },
    ],
    correctChoiceId: 'B',
    explanation: 'Tracking purchases and paying on time helps prevent growing debt and late fees.',
  },
  {
    id: 29,
    category: 'Debt, Loans & Credit Cards',
    question: 'What happens if credit card balances are ignored?',
    choices: [
      { id: 'A', text: 'Debt may grow' },
      { id: 'B', text: 'Savings increase' },
      { id: 'C', text: 'Income increases' },
      { id: 'D', text: 'Budget improves' },
    ],
    correctChoiceId: 'A',
    explanation: 'Unpaid balances can grow through interest, penalties, and new purchases.',
  },
  {
    id: 30,
    category: 'Debt, Loans & Credit Cards',
    question: 'What is the first step toward financial literacy?',
    choices: [
      { id: 'A', text: 'Understanding your money' },
      { id: 'B', text: 'Investing immediately' },
      { id: 'C', text: 'Taking loans' },
      { id: 'D', text: 'Buying insurance' },
    ],
    correctChoiceId: 'A',
    explanation: 'Financial literacy begins with understanding where money comes from, where it goes, and how it affects your financial future.',
  },
]
